import CurrentUserProvider from "@/providers/CurrentUserProvider"
import { IconRaizColored, SetupLayout } from "@/shared"
import { Currency } from "lucide-react"

export const metadata = {
  title: "RAIZ",
  description: "Generated by create next app",
}

export default function BudgetLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <CurrentUserProvider>
        <main className=' bg-neutral-20 min-h-screen '>{children}</main>
      </CurrentUserProvider>
    </>
  )
}
