export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function ProfileLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<main>
			<div className=' bg-grey  '>{children}</div>
		</main>
	)
}
