import CurrentUserProvider from "@/providers/CurrentUserProvider"

export const metadata = {
  title: "RAIZ",
  description: "Generated by create next app",
}

export default function SendLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <CurrentUserProvider>
      <main>
        <div className=' bg-grey min-h-screen '>
          <div className=' '>{children}</div>
        </div>
      </main>
    </CurrentUserProvider>
  )
}
