import { VerifyModal } from "@/components"
import CurrentUserProvider from "@/providers/CurrentUserProvider"
import { DashboardHeader, QrCode, Sidebar } from "@/shared"

export const metadata = {
  title: "RAIZ",
  description: "Generated by create next app",
}

function Dashboardlayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <CurrentUserProvider>
        <VerifyModal />
        <div className=' bg-neutral-20 min-h-screen  '>
          <div className=' h-full  '>
            <QrCode />

            <Sidebar />
            <DashboardHeader />
            <div className='lg:ml-[144px] lg:px-12   '>{children}</div>
          </div>
        </div>
      </CurrentUserProvider>
    </>
  )
}

export default Dashboardlayout
