export const metadata = {
    title: "RAIZ",
    description: "Generated by create next app",
  }
  
  export default function RequestLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <main>
        <div className=' bg-grey min-h-screen '>
          <div className=' '>{children}</div>
        </div>
      </main>
    )
  }
  