import { ReactQueryProvider } from "@/shared"
import "./globals.css"
import React from "react"
import { Toaster } from "@/components/ui/toaster"
import Script from "next/script"

import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google"

export const metadata = {
  title: "RAIZ",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <GoogleAnalytics gaId='G-Y3EY548EHD' />
      <GoogleTagManager gtmId='GTM-TSZW6DZ3' />

      <body className='  '>
        <div className='  '>
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster />
        </div>
      </body>
    </html>
  )
}
