export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function FundLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<main>
			<div className=' bg-grey min-h-screen '>
				<div className='max-w-[1440px] mx-auto'>{children}</div>
			</div>
		</main>
	)
}
